# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-20 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_img',
            field=models.FileField(default='articleimg/default.png', upload_to='articleimg/'),
        ),
    ]
