# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-20 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190220_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('desc', models.CharField(max_length=255)),
                ('avatar', models.FileField(default='articleimg/default.png', upload_to='articleimg/')),
                ('content', models.TextField()),
                ('create_time', models.DateField()),
                ('categorys', models.ManyToManyField(to='blog.Category')),
                ('tags', models.ManyToManyField(to='blog.Tag')),
            ],
        ),
    ]
