# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-20 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190220_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
