# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-20 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190220_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorys',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Tag'),
        ),
    ]
